name:                morse
version:             0.1.0.0
github:              "hr82al/morse"
license:             BSD3
author:              "Aleksander Khromov"
maintainer:          "hr82al@gmail.com"
copyright:           "2022 Aleksander Khromov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hr82al/morse#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- QuickCheck

ghc-options:
- -Wall -fwarn-tabs

library:
  source-dirs: src

executables:
  morse:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morse

tests:
  morse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-orphans
    dependencies:
    - morse
